#! /bin/bash

echo "Make sure you have installed zsh and git"

read hello
echo $hello

sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

echo "Finish installing oh-my-zsh"
echo "###########################"







echo "Please change zsh theme into *agnoster* in .zshrc"
