"set clipboard=unnamedplus

set number

syntax on
set showmode

set encoding=utf-8

set autoindent
set tabstop=4
set expandtab
set softtabstop=4

setlocal spell
set spelllang=en
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
hi clear SpellBad
hi SpellBad cterm=underline
" Set style for gVim
hi SpellBad gui=undercurl
hi SpellBad ctermfg=red ctermbg=black 
hi SpellCap cterm=bold ctermfg=blue ctermbg=black

:nmap L J
:nmap H K
:nmap J 5j
:nmap K 5k

vnoremap Y "+y


call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'lervag/vimtex'
Plug 'sirver/ultisnips'
Plug 'jiangmiao/auto-pairs'
call plug#end()
let NERDTreeWinPos='right'
let NERDTreeWinSize=30
map <F2> :NERDTreeToggle<CR>

let g:tex_flavor='xelatex'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories = ['/home/ahacad/Workstation/Ultisnips-config/config']


