distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun May  2 20:31:32 2021"
installation_id: "e0231840-cd78-4534-bc9d-95150744cede"
rime_version: 1.9.0
update_time: "Mon Oct 16 00:44:42 2023"