distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun May  2 20:12:59 2021"
installation_id: "7fd20285-dfb4-46ac-85a1-0d250794262d"
rime_version: 1.7.3