distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Sun May  2 20:31:32 2021"
installation_id: "e0231840-cd78-4534-bc9d-95150744cede"
rime_version: 1.8.5
update_time: "Tue Feb 21 15:45:40 2023"