#! /bin/bash

external_monitor=$(xrandr --query | grep '^DP-2')
if [[ $external_monitor != *disconnected* ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 mode 2560x1440 --rotate normal --right-of eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5 "infra" 7 8 9 0
    bspc monitor HDMI-1 -d 1 2 "dev" "research" "fin" "draw" 7 8 9 0
else
    xrandr --output HDMI-3 --primary --mode 2560x1440 --rotate normal --rate 144
    bspc monitor -d "prim" "second" "dev" 4 "infra" 6 "draw" "jap" "eng" "ivt"
fi
