#! /bin/bash

external_monitor=$(xrandr --query | grep '^DP-1')
if [[ $external_monitor != *disconnected* ]]; then
    xrandr --output eDP-1 --primary --mode 2160x1440 --rotate normal --output DP-1 mode 2560x1440 --rotate normal --right-of eDP-1
    bspc monitor eDP-1 -d 1 2 3 4 5
    bspc monitor DP-1 -d 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi
