#! /bin/bash
alias tat="tmux attach -t"
alias kl="khal calendar"
alias ikl="ikhal"
cd_ls()
{
    \cd $1
    ls
}
alias cd="cd_ls"
ev_and()
{
    \evince $1 &
}
alias vim="nvim"
alias v="vim"
alias mnho="sudo mount /dev/nvme0n1p11 /media/HOME"
alias mnsg="sudo mount /dev/sda1 /media/Seagate-next"
alias mnwk="sudo mount /dev/nvme0n1p8 /media/Work"
alias startup="mnho ; mnsg ; mnwk ; sudo /usr/bin/NetworkManager; sudo powertop --auto-tune; startx; nm-applet &; ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3"

# just to make it shorter
alias lg=lazygit
alias ldk="/home/ahacad/PROGRAMS/lazydocker"
alias ra=ranger
alias nb=newsboat
alias lc="ll | column"
alias q="cd /media/Work/Work"
alias f="cd /media/Work/PROCESS && lf"
alias p="cd /media/Work/Fudan && lf"
move_to_rubbish() {
    mv $1 "/home/ahacad/Rubbish"
}
alias rm="move_to_rubbish"
#alias pgc="proxychains git clone"
#alias dolt="~/PROGRAMS/dolt-linux-amd64/bin/dolt"
#alias pc="proxychains"
source "/home/ahacad/.config/SELFMADE/shell-shortcuts"
alias bl="betterlockscreen -l --text λ"
alias tmux-session="/home/ahacad/.config/SELFMADE/scripts/tmuxsession.sh"
