#! /bin/bash

CHEATSHEETS="/home/ahacad/Workstation/LEARNING/CHEATSHEETS"

case $2 in 
-t)  for file in `ls $CHEATSHEETS`;
     do
        if [ $file = $1 ]
        then 
            `typora $CHEATSHEETS"/"$1 &`
        fi
     done
     ;;

*)   for file in `ls $CHEATSHEETS`;
     do
        if [ $file = $1 ]
        then 
            cat $CHEATSHEETS"/"$1 | less
        fi
     done
     ;;
esac
