#! /bin/sh

# Status bar
$HOME/.config/polybar/launch &
# Use correct pointer when hovering over background rather than the 'X' cursor
xsetroot -cursor_name left_ptr &
# Key map
killall xcape
killall sxhkd
#setxkbmap -option "ctrl:nocaps, \
                  #shift:both_capslock, \
                  #altwin:swap_lalt_lwin"
#xcape
sxhkd &
ibus-daemon -drx &

# Auto lock screen
#xautolock -time 10 -corners ---- -locker slock &
#xss-lock slock &

# Monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Workspace
if [ -x $HOME/.config/bspwm/executable/bspwm_dual_laptop_setup ]; then
    $HOME/.config/bspwm/executable/bspwm_dual_laptop_setup
fi
# Border
bspc config border_width 1
# Gap
bspc config window_gap   15
# Color
bspc config normal_border_color   "#282c34"
bspc config focused_border_color  "#5c6370"
bspc config presel_feedback_color "#5c6370"
# Monocule
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true
# Float
bspc rule -a Lxappearance         state=floating
bspc rule -a mpv                  state=floating
bspc rule -a Surf                 state=tiled
bspc rule -a Zathura              state=tiled
# Mouse
bspc config swallow_first_click true
# Mouse drag
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
# auto focus when mouse enters a window
bspc config focus_follows_pointer true
# Scratchpad
st -c scratchsmall -g 120x34 &
bspc rule -a scratchsmall sticky=on state=floating hidden=on
#st -c scratchbig -g 170x50 &
bspc rule -a 'scratchbig' sticky=on state=floating hidden=on rectangle=1450x1000+300+200
alacritty --class 'scratchbig' --title bigscratch &
bspc rule -a 'scriptlauncher' sticky=on state=floating hidden=on rectangle=1376x825+300+300
alacritty --class 'scriptlauncher' --title launch &

# start ibus
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3

# autostart scripts (see the file for details)
~/.config/bspwm/executable/autostart.sh &
