name: Neovim Configuration Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: henriquehbr/selene:0.14.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run lint
      shell: bash
      run: /selene --config lint/config.toml lua
