#!/bin/sh

# Terminate already running bar instances
polybar-msg cmd quit

# Auto detect hardware
export WLAN="$(ls /sys/class/net | grep wl)"
export ETHERNET="$(ls /sys/class/net | grep en)"
export THERMAL="$(grep -Rl "x86_pkg_temp" /sys/class/thermal/thermal_zone*/type | tr -d -c 0-9)"

# Launch Polybar, using default config location ~/.config/polybar/config
# for m in $(polybar --list-monitors | cut -d":" -f1); do
#     MONITOR=$m polybar --reload topbar &
# done

screens=$(xrandr --listactivemonitors | grep -v "Monitors" | cut -d" " -f6)
if [[ $(xrandr --listactivemonitors | grep -v "Monitors" | cut -d" " -f4 | cut -d"+" -f2- | uniq | wc -l) == 1 ]]; then
  MONITOR=$(polybar --list-monitors | cut -d":" -f1) TRAY_POS=right polybar main &
else
  primary=$(xrandr --query | grep primary | cut -d" " -f1)

  for m in $screens; do
    if [[ $primary == $m ]]; then
        MONITOR=$m polybar main &
    else
        MONITOR=$m polybar secondary &
    fi
  done
fi
